apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: deploy-3scale-dev-products
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: argo-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: deploy-3scale-dev-products-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: 3scale-dev
      source:
        repoURL: https://github.com/mcaballol/gitops-deploy-3scale-config.git
        targetRevision: main
        path: helms/3scale-helm-product
        helm:
          valueFiles: 
          - /credito-web/config/products/values.yaml
      destination:
        namespace: 3scale-dev
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=false
