---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  generation: 1
  name: 3scale-dev
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'