
---
kind: DeveloperAccount
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: {{ regexReplaceAll "_" (lower $.Values.account.orgName) "-" }}
spec:
  orgName: {{ $.Values.account.orgName }}
  providerAccountRef:
    name: {{ $.Values.tenant_secret }}
---
kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: {{ regexReplaceAll "_" (lower $.Values.account.username) "-" }}
spec:
  developerAccountRef:
    name:  {{ regexReplaceAll "_" (lower $.Values.account.orgName) "-" }}
  email: {{ $.Values.account.email }}
  role: admin
  username: {{ $.Values.account.username }}
  passwordCredentialsRef:
    name: {{ regexReplaceAll "_" (lower $.Values.account.username) "-" }}-account-secret
  providerAccountRef:
    name: {{ $.Values.tenant_secret }}