{{- range $product := .Values.products }}
---
apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: {{ regexReplaceAll "_" (lower $product.name) "-" }}
spec:
  applicationPlans:
    {{ regexReplaceAll "-" $product.plan "_" }}: 
      name: {{ $product.plan }} 
      published: true
  providerAccountRef:
    name: {{ $.Values.tenant_secret }}
    #namespace: 3scale
  name: {{ regexReplaceAll "-" $product.name "_" }}
  systemName: {{ regexReplaceAll "-" $product.name "_" }}
  description: {{ $product.description }}
  backendUsages:
    {{- toYaml $product.backendUsages | nindent 4 }}
  deployment:
    apicastSelfManaged:
      stagingPublicBaseURL: {{ $product.stagingPublicBaseURL }}
      productionPublicBaseURL: {{ $product.productionPublicBaseURL }}
      authentication:
        oidc:
            {{- toYaml $product.oidc | nindent 10 }}

  policies:
    - configuration:
        allow_headers:
          - "Access-Control-Allow-Origin"
          - "Authorization"
      enabled: true
      name: cors
      version: builtin
    - configuration: {}
      enabled: true
      name: apicast
      version: builtin
{{- end }}
