##############################################################
### Para crear de los recursos, ejecutar 'helm template .' ###
##############################################################

tenant_secret: dev-tenant-secret
account:
  email: adminapp@example.cl
  orgName: EXPL
  username: EXPLUSER
  password: EXPLPASS

products:
- name: creditoagil_ext
  description: Proyecto dirigido a DS
  plan: creditoagil-ds
  stagingPublicBaseURL: "https://ext-stg-api-creditoagil.example.cl:443"
  productionPublicBaseURL: "https://ext-api-creditoagil.example.cl:443"
  oidc:
    issuerType: "keycloak"
    issuerEndpoint: "https://3scale-admin-prod-ds:df11bb2c-d74c-458d-862a-blahblah@sso.example.cl/auth/realms/cred-web"
    authenticationFlow:
      standardFlowEnabled: true
      implicitFlowEnabled: false
      serviceAccountsEnabled: false
      directAccessGrantsEnabled: false
    jwtClaimWithClientID: "azp"
    jwtClaimWithClientIDType: "plain"
    credentials: "headers"
    security: 
      secretToken: Shared_secret_sent_from_proxy_to_API_backend_5807a0b75ff275bc
  backendUsages:
    credweb_fis_back:
      path: /v1/back
    credweb_fis_backact:
      path: /v1/backAct
    credweb_fis_cargararchivo:
      path: /v1/credito/upload
    credweb_fis_clientes:
      path: /v1/cliente
    credweb_fis_download:
      path: /v1/download
    credweb_fis_registrocredito:
      path: /v1/credito
    credweb_fis_serv_btt:
      path: /v1
    credweb_node_gateway:
      path: /api/v1
    credweb_api_pdf_convertions:
      path: /api/v1/convert-docs
    credweb_framework_moleculer:
      path: /api/general-user-data
    credweb_service_node:
      path: /api
    credweb_servicio_fis_simuladorcreditoappfin:
      path: /v1/simulacion
    credweb_moleculer_orq:
      path: /api/orq
    apiGenerica_simulador_credito:
      path: /simulacion-credito