{{- range $backend := .Values.backends }}
---
apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: {{ regexReplaceAll "_" (lower $backend.name) "-" }}
spec:
  description: ""
  name: {{ regexReplaceAll "-" $backend.name "_" }}
  privateBaseURL: '{{ $backend.privateBaseURL }}'
  providerAccountRef:
    name: {{ $.Values.tenant_secret }}
    #namespace: 3scale
  systemName: {{ regexReplaceAll "-" $backend.name "_" }}
  methods: 
    {{ regexReplaceAll "-" $backend.name "_" }}:
      friendlyName: {{ regexReplaceAll "-" $backend.name "_" }}
  {{- if or $backend.mappingRules $backend.mappingRules }}
  mappingRules:
    {{- range $mrule := $backend.mappingRules }}
    - httpMethod: {{ $mrule.httpMethod }}
      pattern: {{ $mrule.pattern }}
      metricMethodRef: {{ regexReplaceAll "-" $backend.name "_" }}
      increment: 1
      last: false
    {{- end }}
  
  {{- end }}
{{- end }}
